"""Pydantic Schemas for Phase 5 Agentic AI Investigation System."""

from typing import Dict, Any, List, Optional
import datetime
from pydantic import BaseModel, Field
from enum import Enum


class RecommendedActionEnum(str, Enum):
    ALLOW = "ALLOW"
    MONITOR = "MONITOR"
    STEP_UP_VERIFICATION = "STEP_UP_VERIFICATION"
    RATE_LIMIT = "RATE_LIMIT"


class ToolCallRecord(BaseModel):
    """Auditable trace of an individual investigation tool execution."""
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    result_summary: str
    execution_time_ms: float = 0.0


class InvestigationRequest(BaseModel):
    """Request payload for triggering an AI agent investigation on a transaction."""
    transaction_id: str = Field(..., description="ID of the stored transaction to investigate")
    force_llm: Optional[bool] = Field(default=False, description="Force LLM inference even for low risk")
    analyst_notes: Optional[str] = Field(default=None, description="Optional analyst context notes")


class InvestigationReport(BaseModel):
    """Complete structured dossier generated by the LangGraph Investigation Agent."""
    investigation_id: str
    transaction_id: str
    investigation_status: str = "COMPLETED"  # "COMPLETED", "FALLBACK_DETERMINISTIC", "FAILED"
    
    # Preserved Deterministic Scores (Never invented or modified by LLM)
    risk_score: float
    risk_level: str
    fraud_probability: Optional[float] = None
    anomaly_score: Optional[float] = None
    graph_risk_score: Optional[float] = None
    
    # Evidence & Topological Findings
    key_evidence: List[str] = Field(default_factory=list)
    investigation_findings: List[str] = Field(default_factory=list)
    related_entities: List[str] = Field(default_factory=list)
    fraud_ring_detected: bool = False
    cluster_id: Optional[str] = None
    cluster_size: Optional[int] = None
    
    # Bounded Action Recommendation
    recommended_action: str  # ALLOW, MONITOR, STEP_UP_VERIFICATION, RATE_LIMIT
    confidence: float = 0.90
    explanation: str
    
    # Auditable Process Metadata
    tools_used: List[str] = Field(default_factory=list)
    tool_calls: List[ToolCallRecord] = Field(default_factory=list)
    investigation_path: List[str] = Field(default_factory=list)
    latency_ms: int = 0
    created_at: str = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat())


class AuditLogRecord(BaseModel):
    """Immutable audit trail record for compliance and investigation reproducibility."""
    investigation_id: str
    transaction_id: str
    timestamp: str
    deterministic_inputs: Dict[str, Any]
    tools_executed: List[ToolCallRecord]
    investigation_path: List[str]
    final_verdict: Dict[str, Any]
    fallback_invoked: bool = False
