version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: '{"timestamp":"%(asctime)s", "level":"%(levelname)s", "logger":"%(name)s", "line":%(lineno)d, "message":"%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
loggers:
  razorguard:
    level: DEBUG
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
